FROM nginx:latest
RUN mv /usr/share/nginx/html/index.html /usr/share/nginx/html/OLD.index.html
ADD www /usr/share/nginx/html

#RUN apt-get update
#RUN apt-get upgrade
#RUN apt-get install -y nodejs
#RUN apt-get install -y npm

#RUN node /usr/share/nginx/html/app.js
